name: Daedalus
version: 1.1
main: com.magmaguy.freeminecraftmodels.Daedalus
api-version: '1.21.8'
commands:
    daedalus:
        description: Daedalus plugin command
        usage: /daedalus spawn <model> <amount>
        permission: daedalus.command