name: Daedalus
version: 1.1
main: de.erethon.daedalus.Daedalus
api-version: '1.21.7'
commands:
    daedalus:
        description: Daedalus plugin command
        usage: /daedalus spawn <model> <amount>
        permission: daedalus.command